spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8090/
          predicates:
              - Path=/clients/**
        - id: product-service
          uri: http://localhost:8091/
          predicates:
                - Path=/config
                - Path=/products/**